name: first workflow 
on:
  push:
    branches:
      - main
jobs:
  example-job:
    runs-on:ubuntu-latest
    steps:
      - name: Print welcome massege 
     run: echo "welcome to our first Github Action Workflow !"
